import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api, RouterOutputs } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user?.id);

  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <img
        src={user.profileImageUrl}
        alt="User Profile Image"
        className="h-16 w-16 rounded-full"
      />
      <input
        type="text"
        placeholder="Typing..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (properties: PostWithUser) => {
  const { post, author } = properties;
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <img
        src={author.profileImageUrl}
        alt="User Profile Image"
        className="h-16 w-16 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>{`@${author.username}`}</span>
          <span className="font-thin">{`. 1 hour ago`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="bg-white-300 h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex justify-center">
                <SignOutButton />
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex justify-center">
                <CreatePostWizard />
              </div>
            )}
          </div>
          {/* <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" /> */}
          <div className="flex flex-col">
            {[...data]?.map((fullPost) => (
              <PostView key={fullPost.post.id} {...fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
